export const ROUTES = {
    home: "/feed",
    login: "/login",
    register: "/register",
    book: "/books/:bookId",
    publishers: "/publishers",
    publisher: "/publishers/:publisherId/details",
    profile: "/profile",
    profileLikedBooks: "/profile/liked",
    users: "/users",
    user: "/users/:userId",
    publicUserProfile: "/users/:userId/profile",
    categories: "/categories",
    category: "/categories/:categoryId/details",
    submitBook: "/book/submit",
    updateBook: "/book/update/:bookId",
    error: "/error",
};
